title: Changkat Primary School
url: https://changkatpri.moe.edu.sg
favicon: /images/Site/changkat pri logo.jpg
colors:
  primary-color: "#307fff"
  secondary-color: "#7ed321"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: >-
  Changkat Primary School was initially named Changkat Changi Primary School
  because of its location. It was built on the top of a small hill (“changkat”
  means small hill in Malay) at Changi Road.


  In 1988, the school moved to the present premises and was renamed Changkat
  Primary School. In 2002, the school was scheduled for upgrading under PRIME.
  The school thus shifted to No.7, Jalan Tiga Ratus and occupied the old school
  premises. In June 2004, Changkat Primary moved back to its present premises at
  Simei Street 3
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1vexrv91kdnoi.amplifyapp.com
prod: https://master.d1vexrv91kdnoi.amplifyapp.com
shareicon: /images/Site/changkat pri logo.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
